model_path: "/home/kaylor/work/kaylor/nvidia/FoundationStereo/pretrained_models/small/foundation_stereo.trt"
#model_path: "/home/kaylor/work/kaylor/nvidia/FoundationStereo/pretrained_models/normal/foundation_stereo.trt"
#model_path: "/home/kaylor/work/nvidia/FoundationStereo/pretrained_models/small/foundation_stereo.trt"
#model_path: "/home/kaylor/work/kaylor/nvidia/FoundationStereo/pretrained_models/normal_540/foundation_stereo.trt"
device: "/dev/video0"
width: 2560
height: 720
fps: 60
baseline: 0.1198430
K: [955.8550, 0.0, 655.0450,
    0.0, 955.9950, 363.3060,
    0.0, 0.0, 1.0]
