#model_path: "../model/yolo/yolo11n-seg-local.trt"
#model_path: "../model/yolo/yolo11n-seg.onnx"
#model_path: "../model/yolo/yolo11n-seg.om"
#model_path: "../model/yolo/yolo.rknn"
#model_path: "../model/yolo/yolo.om"
#model_path: "../model/yolo/yolo.trt"
#model_path: "../model/yolo/yolo11n.rknn"
#model_path: "../model/yolo/yolov13n.rknn"
#model_path: "../model/yolo/yolo11n.om"
#model_path: "../model/yolo/yolov13n.om"
#model_path: "../model/yolo/yolo11n.trt"
#model_path: "../model/yolo/yolo11n-pose.rknn"
#model_path: "../model/yolo/20260115/yolov8n.rknn"
model_path: "../model/yolo/20260115/yolo26n.rknn"
#model_path: "../model/yolo/20260115/yolo11n.rknn"
#model_path: "../model/yolo/yolo26/yolo.rknn"
#model_path: "../model/yolo/yolo26/yolo.trt"
#model_path: "../model/yolo/yolo11n-pose.trt"
#model_path: "../model/yolo/yolov13n.trt"
#model_path: "../model/yolo/yolo11n-seg.rknn"
video_path: "../model/video/rose.mp4"
video_play_fps: 25
thread_num: 1
cv_show: true
